DROP TABLE BOOKS Cascade Constraints PURGE;
DROP TABLE CATEGORIES Cascade Constraints PURGE; 
DROP TABLE CATEGORIES_BOOKS Cascade Constraints PURGE;                           
DROP TABLE CDS Cascade Constraints PURGE ;                
DROP TABLE STOCKS Cascade Constraints PURGE ;                
DROP TABLE BASE_COUNTRY Cascade Constraints PURGE;
DROP TABLE NAMES Cascade Constraints PURGE;                      
DROP TABLE ADDRESS Cascade Constraints PURGE;                    
DROP TABLE AUTHORS Cascade Constraints PURGE ;                                  
DROP TABLE AUTHORS_BOOKS Cascade Constraints PURGE;                           
DROP TABLE USERS Cascade Constraints PURGE;
DROP TABLE PASSWORDS Cascade Constraints PURGE;
DROP TABLE USERS_ADDRESS Cascade Constraints PURGE;                           
DROP TABLE PUBLISHERS Cascade Constraints PURGE;  
DROP TABLE PRICES Cascade Constraints PURGE;       
DROP TABLE COMMENTS Cascade Constraints PURGE;                  
DROP TABLE GENERES Cascade Constraints PURGE;                  
DROP TABLE BOOK_IMAGES Cascade Constraints PURGE; 
DROP TABLE CD_IMAGES Cascade Constraints PURGE; 
